# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Filipe Portfólio
email: filipernobrega@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Conheça umm pouco mais sobre os projetos que desenvolvi. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: 
# github_username:  
instagram_username: 366wines
linkedin_username: frnobrega
# stackoverflow_username:

# Build settings
port: 3000
markdown: kramdown
highlighter: rouge # Supported Languages https://github.com/rouge-ruby/rouge/wiki/List-of-supported-languages-and-lexers

livereload: true

theme: minima
plugins:
  - jekyll-feed
  - jekyll-pwa-plugin
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
- scope:
    path: "assets/img"
  values:
    image: true

# Assets settings 
sass:
    sass_dir: _sass

pwa:
  enabled: false # Optional
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
  precache_glob_ignores: # Optional
    - sw-register.js
    - "fonts/**/*"


# Locale settings 

locales:
  default:
    baseurl: ""
    name: 🇺🇸
    lang: en-US
  pt:
    baseurl: /pt
    name: 🇧🇷
    lang: pt-PT

collections:
  pages_pt:
    output: true
    permalink: /pt/:path/
  posts_pt:
    output: true
    permalink: /pt/blog/:categories/:title/

permalink: pretty

defaults:
# set page.collection_basename to match collections
- scope:
    type: pages
  values:
    layout: page
    collection_basename: pages
- scope:
    path: "_pages*/"
  values:
    layout: page
    collection_basename: pages
- scope:
    path: "_posts*/"
  values:
    layout: post
    collection_basename: posts
# set page.locale, page.lang, page.collection_suffix
- scope:
    path: "*_pt/"
  values:
    locale: pt
    lang: pt-PT
    collection_suffix: _pt
- scope:
    path: ""
  values:
    locale: default
    lang: en-US
# prevent index pages from publishing to baseurl/index/index.html
- scope:
    path: "_pages_pt/index.*"
  values:
    permalink: "/pt/"
  
navigation:
- index
- works
- blog
- posts-list
# - spotify
- about
- contact


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
